---
- hosts: localhost
  connection: local
  become: yes
  tasks:
    - name: Download kubectl
      command: "curl -LO {{https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl}}"
    - name: Install kubectl
      command: "install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl"      
